server:
  port: 8080
spring:
  application:
    name: "CrediYa"
  devtools:
    add-properties: false
  flyway:
    url: "jdbc:postgresql://localhost:5432/crediya"
    user: "postgres"
    password: "Misional123@"
    locations: "classpath:db/migration"
    enabled: false
adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "crediya_usuarios"
    schema: "public"
    username: "postgres"
    password: "Misional123@"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

routes:
  paths:
    tasks: "/api/v1/usuarios"
    tasksById: "/api/v1/usuarios/{identification}"

springdoc:
  swagger-ui:
    path: "/api/doc/swagger-ui.html"
  api-docs:
    path: "/api/doc/api-docs"